#!/usr/bin/env python
# Author : ricardoftribeiro@gmail.com @krfribeiro
# -*- coding: utf-8 -*-


def agent_graphite_arguments(params, hostname, ipaddress):
    args = ''

    args += " -v " + quote_shell_string(",".join(params["values"]))

    if "user" in params:
        args += " -u " + quote_shell_string(params["user"])
    if "password" in params:
        args += " -p " + quote_shell_string(params["password"])

    args += " " + quote_shell_string(ipaddress)

    return args

special_agent_info['graphite'] = agent_graphite_arguments