#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-


def agent_graphite_arguments(params, hostname, ipaddress):
    args = ''

    args += " -v " + quote_shell_string(",".join(params["values"]))

    if "user" in params:
        args += " -u " + quote_shell_string(params["user"])
    if "password" in params:
        args += " -p " + quote_shell_string(params["password"])

    args += " " + quote_shell_string(ipaddress)

    return args

special_agent_info['graphite'] = agent_graphite_arguments