#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# GDC - Monitorizacao Datacenter
# Fortinet Firewalls Virtual Domain MEM Usage
#
# fgVdTable
#
# snmpwalk -On -v2c -c <COMMUNITY> <IP> .1.3.6.1.4.1.12356.101.3.2.1.1
#
#  .1.3.6.1.4.1.12356.101.3.2.1.1.2 Virtual Domain Name
#  .1.3.6.1.4.1.12356.101.3.2.1.1.6 Virtual Domain MEM Usage


factory_settings["fortigate_vdom_mem_default_levels"] = {
    "memlevels"                 :       (90,95),
}

def inventory_fortigate_vdoms_mem(info):
    inventory = []
    for line in info:
        inventory.append((line[0],fortigate_vdom_mem_default_levels))
    return inventory

def check_fortigate_vdoms_mem(item, params, info):
    for line in info:
       if line[0] == item:
           global g_counters
           warn, crit = params.get("memlevels")
           perfdata = []
           mem_usage = int(line[1])
           for dir, value in [ ('MEMUsage', int(line[1])) ]:
               perfdata.append(( dir, saveint(value) ))
           if mem_usage >= crit:
               return (2, "CRIT - Virtual Domain Memory is %s %% used" % mem_usage , perfdata)
           elif mem_usage >= warn:
               return (1, "WARN - Virtual Domain Memory is %s %% used" % mem_usage , perfdata)
           else:
               return (0, "OK - Virtual Domain Memory is %s %% used" % mem_usage , perfdata)
    return (3, "UNKNOWN - Virtual Domain %s not found in SNMP output" % item)

check_info["fortigate_vdoms_mem"] = {
    "check_function"        : check_fortigate_vdoms_mem,
    "inventory_function"    : inventory_fortigate_vdoms_mem,
    "service_description"   : "Virtual Domain Memory - %s",
    "has_perfdata":         True,
    "group"                 : "fortigate_vdoms_mem",
    "default_levels_variable" : "fortigate_vdom_mem_default_levels",
    "snmp_info"             : ( ".1.3.6.1.4.1.12356.101.3.2.1.1", [ "2", "6" ] ) }
