#!/usr/bin/env python
# Author : ricardoftribeiro@gmail.com @krfribeiro
# -*- coding: utf-8 -*-
# Fortigate Hardware Sensor Table
#
# fgHwSensorEntry
#
# snmpwalk -v2c -c <COMMUNITY> <IP> .1.3.6.1.4.1.12356.101.4.3.2.1
# .1.3.6.1.4.1.12356.101.4.3.2.1
# .2 # Name
# .4 # Status
#

def inventory_fortinet_hardware(info):
    inventory = []
    for line in info:
        inventory.append((line[0],None))
    return inventory

def check_fortinet_hardware(item, _no_params, info):
    for line in info:
       if line[0] == item:
           status = int(line[1])
           if status != 0:
               return (2, "CRIT - %s in critical state" % item )
           else:
               return (0, "OK - %s is OK" % item )
    return (3, "UNKNOWN - Power Supply %s not found in SNMP Output" % item)

check_info["fortinet_hardware"] = {
    "check_function"        : check_fortinet_hardware,
    "inventory_function"    : inventory_fortinet_hardware,
    "service_description"   : "FG - %s",
    "snmp_info"             : ( ".1.3.6.1.4.1.12356.101.4.3.2.1", [ "2", "4" ] ) }
