#!/usr/bin/env python
# Author : ricardoftribeiro@gmail.com @krfribeiro
# -*- coding: utf-8 -*-
# Huawei FAN Status
#
# fanDescriptionTable
#
# snmpwalk -v2c -c <COMMUNITY> <IP> .1.3.6.1.4.1.2011.2.235.1.1.8.50.1
#	.3  fanPresence
#	.4  fanStatus
#	.7  fanDeviceName
#

def inventory_huaweiibmc_fan(info):
    inventory = []
    for line in info:
        inventory.append((line[2],None))
    return inventory

def check_huaweiibmc_fan(item, _no_params, info):
    for line in info:
       if line[2] == item:
           status = int(line[0])
           if status >= 3:
               return (2, "CRIT - FAN in critical state" )
           else:
               return (0, "OK - FAN is OK")
    return (3, "UNKNOWN - FAN %s not found in SNMP Output" % item)

check_info["huaweiibmc_fan"] = {
    "check_function"        : check_huaweiibmc_fan,
    "inventory_function"    : inventory_huaweiibmc_fan,
    "service_description"   : "FAN %s",
    "snmp_info"             : ( ".1.3.6.1.4.1.2011.2.235.1.1.8.50.1", [ "3", "4", "7" ] ) }
