#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# GDC - Monitorizacao Datacenter
# Huawei Power Supply Status
#
# powerSupplyDescriptionEntry
#
# snmpwalk -v2c -c <COMMUNITY> <IP>  .1.3.6.1.4.1.2011.2.235.1.1.6.50.1
# .1.3.6.1.4.1.2011.2.235.1.1.6.50.1
# .7 # Status
# .13 # Name
#

def inventory_huaweiibmc_psus(info):
    inventory = []
    for line in info:
        inventory.append((line[1],None))
    return inventory

def check_huaweiibmc_psus(item, _no_params, info):
    for line in info:
       if line[1] == item:
           status = int(line[0])
           if status > 3:
               return (2, "CRIT - Power Supply in critical state" )
           elif status == 2:
               return (1, "WARN - Power Supply in warning (minor) state")
           else:
               return (0, "OK - Power Supply is OK")
    return (3, "UNKNOWN - Power Supply %s not found in SNMP Output" % item)

check_info["huaweiibmc_psus"] = {
    "check_function"        : check_huaweiibmc_psus,
    "inventory_function"    : inventory_huaweiibmc_psus,
    "service_description"   : "Power Supply - %s",
    "snmp_info"             : ( ".1.3.6.1.4.1.2011.2.235.1.1.6.50.1", [ "7", "13" ] ) }
