#!/usr/bin/env python
# Author : ricardoftribeiro@gmail.com @krfribeiro
# -*- coding: utf-8 -*-
# Huawei Power Supply Status
#
# memoryDescriptionTable
#
# snmpwalk -v2c -c <COMMUNITY> <IP> .1.3.6.1.4.1.2011.2.235.1.1.16.50.1 
# .6  # memoryStatus 
# .8  # memoryLocation
# .10 # DeviceName
#

def inventory_huaweiibmc_memory(info):
    inventory = []
    for line in info:
        if line[1] != "0": 
            inventory.append((line[2],None))
    return inventory

def check_huaweiibmc_memory(item, _no_params, info):
    for line in info:
       if line[2] == item:
           status = int(line[0])
           if status > 3:
               return (2, "CRIT - Memory in critical state" )
           elif status == 2:
               return (1, "WARN - Memory in warning (minor) state")
           else:
               return (0, "OK - Memory is OK")
    return (3, "UNKNOWN - Memory %s not found in SNMP Output" % item)

check_info["huaweiibmc_memory"] = {
    "check_function"        : check_huaweiibmc_memory,
    "inventory_function"    : inventory_huaweiibmc_memory,
    "service_description"   : "Memory %s Status",
    "snmp_info"             : ( ".1.3.6.1.4.1.2011.2.235.1.1.16.50.1", [ "6", "8", "10" ] ) }
