#!/usr/bin/env python
# Author : ricardoftribeiro@gmail.com @krfribeiro
# -*- coding: utf-8 -*-
# <<<sas_rmi_server>>>
# SAS Remote Services 1 is UP

def inventory_sas_rmi_server(info):
        inventory = []
        for line in info:
                mysite = line[0] + ' ' + line[1] + ' ' + line[2] + ' ' + line[3]
                # mysite = line[0]
                if len(line) > 0:
                        inventory.append( (mysite, None)  )
        return inventory

def check_sas_rmi_server(item, _unused, info):
        for line in info:
                mystate = line[5]
                if mystate == "UP":
                        return (0, "".join(item) + " " + "".join(mystate))
                else:
                        return (2, "".join(item) + " " + "".join(mystate))
        return (3, "UNKNWON - % line")

check_info["sas_rmi_server"] = {
        'check_function':       check_sas_rmi_server,
        'inventory_function':   inventory_sas_rmi_server,
        'service_description':  '%s',
        'has_perfdata':         False,
}
