#!/usr/bin/env python
# Author : ricardoftribeiro@gmail.com @krfribeiro
# -*- coding: utf-8 -*-
#
# VMAX Check (For Check_MK)
# Tested Environmnet
# - OMD 1.20
#
# <<<vmax_ra>>>
# RE-3H Online
# RE-4H Online

def inventory_vmax_ra(info):
	inventory = []
	for line in info:
		mysite = line[0] 
		if len(line) > 0:
			inventory.append( (mysite, None)  )
	return inventory

def check_vmax_ra(item, _unused, info):
	for line in info:
		if line[0] != item:
			continue
		mystate = line[1]
		mysite = line[0]
		if mystate == "Online": 
			return (0, 'OK ' + "".join(item) + " " + "".join(mystate))
		else:
			return (2, 'FAIL ' + "".join(item) + " " + "".join(mystate))
	return (3, "UNKNWON - % line")

check_info["vmax_ra"] = {
	'check_function':	check_vmax_ra,
	'inventory_function':	inventory_vmax_ra,
	'service_description':	'VMAX Replication Port Status %s',
	'has_perfdata':		False,
}
