#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Example output from agent:
# healthcheck Started
# PROD.JMS.CC.WEB.15R101.001(9000) Started
# PROD.JMS.CC.WEB.15R101.001(9000).WEB Started
# PROD.JMS.CC.WEB.15R101.001(9000).WS.API Started
# PROD.JMS.CC.WEB.15R101.001(9000).WS.Leg Started
def inventory_WebAppPool(info):
        return [(name[0], 'None') for name in info]

def check_WebAppPool(item, _unused, info):
    for line in info:
        if line[0] != item:
            continue

        pool_name = line[0]
        pool_state = line[1]
        if pool_state == "Started":
          return 0, ' %s is in state - %s' % (pool_name,pool_state)
        elif pool_state == "Stopped":
          return 2, '[Stopped] %s is in state - %s' % (pool_name,pool_state)
        else:
          return 3, 'Unknown - %s' % (pool_name)

check_info["WebAppPool"] = {
    "check_function"        : check_WebAppPool,
    "inventory_function"    : inventory_WebAppPool,
    "service_description"   : "Web Application Pool -  %s ",
    "has_perfdata"          : False,
}
