#!/usr/bin/env python
# Author : ricardoftribeiro@gmail.com @krfribeiro
# -*- coding: utf-8 -*-

# Example output from agent:
# healthcheck Started
# PROD.JMS.CC.WEB.15R101.001(9000) Started
# PROD.JMS.CC.WEB.15R101.001(9000).WEB Started
# PROD.JMS.CC.WEB.15R101.001(9000).WS.API Started
# PROD.JMS.CC.WEB.15R101.001(9000).WS.Leg Started

def inventory_WebAppPool(info):
        return [(name[0], 'None') for name in info]

def check_WebAppPool(item, _unused, info):
    for line in info:
        if line[0] != item:
            continue

        pool_name = line[0]
        pool_state = line[1]
        if pool_state == "Started":
          return 0, ' %s is in state - %s' % (pool_name,pool_state)
        elif pool_state == "Stopped":
          return 2, '[Stopped] %s is in state - %s' % (pool_name,pool_state)
        else:
          return 3, 'Unknown - %s' % (pool_name)

check_info["WebAppPool"] = {
    "check_function"        : check_WebAppPool,
    "inventory_function"    : inventory_WebAppPool,
    "service_description"   : "Web Application Pool -  %s ",
    "has_perfdata"          : False,
}
