#!/usr/bin/env python
# Author : ricardoftribeiro@gmail.com @krfribeiro
# -*- coding: utf-8 -*-

hp_blade_present_map = { 1: 'other', 2: 'absent', 3: 'present' }

def inv_hp_bladesystem_blades(info):
    node = inv_tree_list("hardware.components.chassis:")
    for bld_index, bld_presence, bld_prodid, bld_name, bld_sn in info:
        if hp_blade_present_map.get(int(bld_presence), "") == 'present':
            node.append({
                "index"         : bld_index,
                "name"          : bld_name,
                "description"   : "Blade",
                "serial"        : bld_sn,
                "model"         : bld_prodid
            })

inv_info['hp_bladesystem_blades'] = {
    'inv_function'       : inv_hp_bladesystem_blades,
    'snmp_info'          : ('.1.3.6.1.4.1.232.22.2.4.1.1.1', ['3', '12', '17', '4', '16']),
    'snmp_scan_function' : lambda oid: ".11.5.7.1.2" in oid(".1.3.6.1.2.1.1.2.0"),
}

# '.1.3.6.1.4.1.232.22.2.4.1.1.1.3'  => 'cpqRackServerBladeIndex',     # Index
# '.1.3.6.1.4.1.232.22.2.4.1.1.1.4'  => 'cpqRackServerBladeName',      # FQDN
# '.1.3.6.1.4.1.232.22.2.4.1.1.1.12' => 'cpqRackServerBladePresent',   # 3 = Present
# '.1.3.6.1.4.1.232.22.2.4.1.1.1.16' => 'cpqRackServerBladeSerialNum', # CZJ1050BMX
# '.1.3.6.1.4.1.232.22.2.4.1.1.1.17' => 'cpqRackServerBladeProductId', # ProLiant BL460c G6